### welikia list from barnard block on manahatta map
BRF_full <- c("Acer pensylvanicum", "Acer rubrum", "Acer saccharinum", "Acer saccharum", 
              "Conioselinum chinense", "Cryptotaenia canadensis", "Hydrocotyle americana", 
              "Apocynum cannabinum", "Ilex verticillata", "Arisaema triphyllum",
              "Symplocarpus foetidus", "Panax trifolius", "Asarum canadense",
              "Cynanchum louiseae", "Asplenium rhizophyllum", "Asplenium trichomanes", 
              "Dryopteris intermedia", "Dryopteris marginalis", "Achillea millefolium", 
              "Ambrosia artemisiifolia", "Anaphalis margaritacea", "Antennaria parlinii", 
              "Antennaria plantaginifolia", "Aster acuminatus", "Aster cordifolius", 
              "Aster divaricatus", "Aster dumosus", "Aster linariifolius", "Aster paternus",
              "Aster pilosus", "Aster sagittifolius", "Aster umbellatus", "Aster vimineus", 
              "Bidens bipinnata", "Bidens cernua", "Bidens connata", "Cirsium discolor", 
              "Erectites hieracifolia", "Erigeron annuus", "Erigeron philadelphicus", 
              "Eupatorium purpureum", "Eupatorium rugosum", "Euthamia graminifolia", 
              "Hieracium paniculatum", "Hieracium venosum", "Lapsana communis", 
              "Leucanthemum vulgare","Rudbeckia hirta", "Senecio obovatus", "Solidago bicolor",
              "Solidago flexicaulis", "Solidago juncea", "Solidago rugosa","Solidago squarrosa",
              "Symphyotrichum novae-angliae", "Taraxacum laevigatum", "Tussilago farfara", 
              "Impatiens capensis", "Impatiens pallida", "Berberis thunbergii", "Alnus incana",
              "Alnus serrulata", "Betula alleghaniensis", "Betula lenta", "Betula populifolia",
              "Carpinus caroliniana", "Ostrya virginiana", "Catalpa bignonioides", 
              "Myosotis laxa", "Myosotis scorpioides", "Alliaria petiolata", "Arabis laevigata",
              "Arabis lyrata", "Barbarea vulgaris", "Cardamine pensylvanica", 
              "Hesperis matronalis", "Callitriche palustris", "Lobelia inflata",
              "Triodanis perfoliata", "Humulus japonicus", "Diervilla lonicera", 
              "Lonicera tartarica", "Sambucus canadensis", "Viburnum acerifolium",
              "Viburnum lentago", "Viburnum nudum", "Viburnum recognitum", "Cerastium fontanum",
              "Dianthus armeria", "Lychnis coronaria", "Paronychia canadensis", 
              "Silene latifolia", "Silene nivea", "Celastrus scandens", "Euonymus alata",
              "Clethra alnifolia", "Hypericum gentianoides", "Hypericum mutilum",
              "Hypericum punctatum", "Triadenum virginicum", "Cornus florida", 
              "Sedum sarmentosum", "Juniperus virginiana", "Cuscuta gronovii", "Carex albicans",
              "Carex amphibola", "Carex baileyi", "Carex blanda", "Carex brunnescens",
              "Carex communis", "Carex comosa", "Carex crinita", "Carex debilis", 
              "Carex disperma", "Carex festucacea", "Carex gracillima", "Carex intumescens", 
              "Carex leptonervia", "Carex lurida", "Carex pedunculata", "Carex pensylvanica",
              "Carex platyphylla", "Carex scoparia", "Carex seorsa", "Carex stipata",
              "Carex stricta", "Carex swanii", "Carex torta", "Carex virescens", 
              "Carex vulpinoidea", "Cyperus strigosus", "Dulichium arundinaceum",
              "Eleocharis acicularis", "Eleocharis obtusa", "Scirpus atrovirens",
              "Dennstaedtia punctilobula", "Drosera intermedia", "Drosera rotundifolia",
              "Dryopteris carthusiana", "Dryopteris clintoniana", "Dryopteris marginalis",
              "Polystichum acrostichoides", "Equisetum arvense", "Equisetum sylvaticum",
              "Chamaedaphne calyculata", "Epigaea repens", "Gaultheria procumbens",
              "Gaylussacia baccata", "Kalmia latifolia", "Monotropa hypopitys", 
              "Monotropa uniflora", "Rhododendron maximum", "Rhododendron periclymenoides",
              "Rhododendron viscosum", "Vaccinium angustifolium", "Vaccinium corymbosum",
              "Vaccinium pallidum", "Acalypha virginica", "Euphorbia cyparissias",
              "Euphorbia esula", "Desmodium nudiflorum", "Lespedeza intermedia",
              "Lespedeza procumbens", "Lotus corniculatus", "Melilotus alba", 
              "Melilotus officinalis", "Trifolium arvense", "Trifolium aureum", 
              "Trifolium campestre", "Trifolium dubium", "Trifolium hybridum", 
              "Trifolium pratense", "Trifolium repens", "Castanea dentata", "Quercus alba", 
              "Quercus ilicifolia", "Quercus montana", "Quercus rubra", "Quercus velutina",
              "Corydalis flavula", "Corydalis sempervirens", "Dicentra cucullaria",
              "Geranium carolinianum", "Geranium maculatum", "Geranium robertianum",
              "Ribes rotundifolium", "Hamamelis virginiana", "Elodea nuttallii",
              "Iris versicolor", "Sisyrinchium angustifolium", "Carya glabra", "Carya ovata",
              "Carya tomentosa", "Juncus acuminatus", "Juncus canadensis", "Juncus effusus",
              "Juncus tenuis", "Luzula campestris", "Ajuga reptans", "Clinopodium vulgare",
              "Hedeoma pulegioides", "Leonurus cardaica", "Lycopus uniflorus", "Mentha arvensis",
              "Nepeta cataria", "Prunella vulgaris", "Pycnanthemum tenuifolium", 
              "Scutellaria lateriflora", "Lindera benzoin", "Sassafras albidum", 
              "Erythronium americanum", "Hypoxis hirsuta", "Maianthemum canadense", 
              "Maianthemum racemosum", "Ornithogalum umbellatum", "Polygonatum biflorum", 
              "Polygonatum pubescens", "Trillium erectum", "Huperzia lucidula", 
              "Lycopodium obscurum", "Liriodendron tulipifera", "Comptonia peregrina",
              "Fraxinus americana", "Syringa vulgaris", "Oenothera perennis",
              "Epipactis heleborine", "Conopholis americana", "Orobanche uniflora", 
              "Oxalis stricta", "Chelidonium majus", "Phytolacca americana", "Larix laricina", 
              "Picea abies", "Picea glauca", "Pinus resinosa", "Pinus rigida", "Pinus strobus", 
              "Tsuga canadensis", "Platanus occidentalis", "Agrostis capillaris", 
              "Agrostis hyemalis", "Agrostis perennans", "Agrostis scabra", 
              "Andropogon gerardii", "Anthoxanthum odoratum", "Brachyelytrum erectum",
              "Bromus commutatus", "Bromus inermis", "Cinna arundinacea", "Dactylis glomerata",
              "Danthonia compressa", "Danthonia spicata", "Deschampsia flexuosa",
              "Dichanthelium latifolium", "Digitaria ischaemum", "Echinochloa crusgalli",
              "Elymus hystrix", "Elymus riparius", "Festuca rubra", "Glyceria canadensis",
              "Leersia virginica", "Lolium perenne", "Muhlenbergia mexicana", 
              "Muhlenbergia tenuiflora", "Panicum acuminatum", "Panicum clandestinum",
              "Panicum dichotomum", "Panicum linearifolium", "Panicum villosissimum",
              "Phleum pratense", "Poa nemoralis", "Schizachyrium scoparium", 
              "Sorghastrum nutans", "Polygala verticillata", "Polygonum aviculare", 
              "Polygonum cespitosum", "Polygonum hydropiper", "Polygonum hydropiperoides", 
              "Polygonum persicaria", "Polygonum punctatum", "Polygonum sagittatum", 
              "Polygonum scandens", "Polygonum virginianum", "Rumex acetosella", 
              "Polypodium virginianum", "Potamogeton spirillus", "Lysimachia nummularia", 
              "Lysimachia quadrifolia", "Lysimachia terrestris", "Adiantum pedatum", 
              "Chimaphila maculata", "Pyrola elliptica", "Actaea  pachypoda", 
              "Anemone quinquefolia", "Aquilegia canadensis", "Clematis virginiana",
              "Ranunculus abortivus", "Ranunculus recurvatus", "Thalictrum dioicum", 
              "Thalictrum thalictroides", "Rhamnus cathartica", "Agrimonia gryposepala",
              "Amelanchier arborea", "Amelanchier canadensis", "Aronia melanocarpa",
              "Crataegus crus-galli", "Fragaria virginiana", "Malus pumila", 
              "Potentilla canadensis", "Potentilla simplex", "Prunus pensylvanica",
              "Prunus virginiana", "Rosa multiflora", "Rubus allegheniensis", "Rubus hispidus",
              "Rubus occidentalis", "Spirea alba", "Spirea salicifolia", 
              "Cephalanthus occidentalis", "Galium mollugo", "Galium obtusum", 
              "Galium triflorum", "Mitchella repens", "Populus deltoides", 
              "Populus grandidentata", "Salix eriocephala", "Salix nigra", "Salix sericea",
              "Chrysosplenium americanum", "Mitella diphylla", "Agalinis tenuifolia",
              "Aureolaria flava", "Gratiola neglecta", "Linaria vulgaris", "Melampyrum lineare",
              "Mimulus ringens", "Pedicularis canadensis", "Veronica arvensis", 
              "Veronica officinalis", "Veronica serpyllifolia", "Smilax rotundifolia", 
              "Solanum dulcamara", "Sparganium americanum", "Sphagnum capillifolium",
              "Sphagnum fallax", "Sphagnum fimbriatum", "Sphagnum fuscum", "Sphagnum palustre",
              "Sphagnum recurvum", "Sphagnum teres", "Thelypteris novaboracensis", 
              "Dirca palustris", "Tyhpa angustifolia", "Tyhpa latifolia", "Ulmus rubra", 
              "Gyrophora muhlenbergii", "Umbilicaria pustulata", "Pilea pumila", 
              "Viola blanda", "Viola conspersa", "Viola cucullata", "Viola macloskeyi", 
              "Viola pubescens", "Viola sororia", "Parthenocissus quinquefolia", 
              "Vitis labrusca", "Acer spicatum", "Alisma subcordatum", "Sagittaria graminea", 
              "Sagittaria latifolia", "Rhus copallinum", "Rhus glabra", "Rhus hirta", 
              "Toxicodendron radicans", "Toxicodendron vernix", "Angelica venenosa", 
              "Cicuta bulbifera", "Cicuta maculata", "Conium maculatum", "Daucus carota",
              "Heracleum maximum", "Osmorhiza claytonii", "Sanicula marilandica", 
              "Sium suave", "Zizia aptera", "Zizia aurea", "Apocynum androsaemifolium", 
              "Nemopanthus mucronatus", "Calla palustris", "Peltandra virginica", 
              "Aralia nudicaulis", "Aralia racemosa", "Aralia spinosa", 
              "Aristolochia serpentaria", "Asclepias exaltata", "Asclepias incarnata", 
              "Asclepias purpurascens", "Asclepias quadrifolia", "Asclepias syriaca",
              "Asplenium platyneuron", "Asplenium trichomanes", "Antennaria neglecta",
              "Arctium minus", "Aster cordifolius", "Aster divaricatus", "Aster ericoides",
              "Aster lanceolatus", "Aster lateriflorus", "Aster linariifolius", 
              "Aster lowrieanus", "Aster macrophyllus", "Aster patens", "Aster puniceus",
              "Aster racemosus", "Aster schreberi", "Bidens coronata", "Bidens frondosa", 
              "Centaurea nigra", "Cichorium intybus", "Cirsium arvense", "Cirsium vulgare", 
              "Conyza canadensis", "Erigeron pulchellus", "Eupatorium perfoliatum", 
              "Eupatorium sessilifolium", "Galinsoga quadriradiata", "Gnaphalium obtusifolium", 
              "Gnaphalium uliginosum", "Helianthus decapetalus", "Helianthus divaricatus", 
              "Heliopsis helianthoides", "Hieracium aurantiacum", "Hieracium caespitosum", 
              "Hieracium paniculatum", "Krigia biflora", "Krigia virginica", 
              "Lactuca canadensis", "Prenanthes altissima", "Prenanthes trifoliata", 
              "Solidago arguta", "Solidago caesia", "Solidago canadensis", "Solidago odora", 
              "Solidago puberula", "Solidago ulmifolia", "Taraxacum officinale", 
              "Xanthium strumarium", "Berberis thunbergii", "Caulophyllum thalictroides", 
              "Betula lenta", "Betula papyrifera", "Corylus cornuta", "Echium vulgare", 
              "Alliaria petiolata", "Arabis canadensis", "Arabis laevigata", "Arabis lyrata",
              "Barbarea vulgaris", "Brassica nigra", "Capsella bursa-pastoris", 
              "Lepidium campestre", "Lepidium virginicum", "Rorippa palustris", 
              "Sinapsis arvensis", "Thlaspi arvense", "Pachysandra terminalis", 
              "Brasenia schreberi", "Callitriche terrestris", "Campanula rotundifolia", 
              "Lobelia cardinalis", "Lobelia dortmanna", "Lobelia siphilitica",
              "Lobelia spicata", "Lonicera dioica", "Lonicera morrowii", "Sambucus racemosa",
              "Viburnum dentatum", "Viburnum lentago", "Viburnum prunifolium", 
              "Viburnum rafinesquianum", "Cerastium arvense", "Cerastium nutans", 
              "Cerastium semidecandrum", "Paronychia canadensis", "Paronychia fastigiata", 
              "Sagina procumbens", "Scleranthus annuus", "Silene antirrhina", "Silene stellata", 
              "Silene vulgaris", "Stellaria graminea", "Celastrus orbiculata", 
              "Celastrus scandens", "Euonymus alata", "Chenopodium album", 
              "Chenopodium standleyanum", "Helianthemum bicknellii", "Helianthemum canadense", 
              "Lechea intermedia", "Lechea mucronata", "Hypericum canadense", 
              "Hypericum gentianoides", "Hypericum perforatum", "Triadenum virginicum", 
              "Commelina communis", "Calystegia sepium", "Convolvulus arvensis", "Cornus amomum",
              "Cornus florida", "Cornus foemina", "Cornus rugosa", "Cornus sericea", 
              "Penthorum sedoides", "Sedum telephium", "Carex aestivalis", "Carex albicans", 
              "Carex albursina", "Carex argyrantha", "Carex atlantica", "Carex bromoides", 
              "Carex brunnescens", "Carex canescens", "Carex cephalophora", "Carex debilis", 
              "Carex digitalis", "Carex foena", "Carex granularis", "Carex gynandra", 
              "Carex hirsutella", "Carex interior", "Carex laevivaginata", "Carex laxiculmis", 
              "Carex laxiflora", "Carex leptalea", "Carex lucorum", "Carex muhlenbergii",
              "Carex normalis", "Carex novae-angliae", "Carex oligocarpa", "Carex pallescens", 
              "Carex peckii", "Carex prasina", "Carex radiata", "Carex rosea", "Carex scabrata",
              "Carex scoparia", "Carex sparganioides", "Carex tribuloides", "Carex vulpinoidea", 
              "Eleocharis elliptica", "Eleocharis obtusa", "Eleocharis palustris", 
              "Scirpus cyperinus", "Scirpus hattorianus", "Scirpus verecundus", 
              "Pteridium aquilinum", "Dioscorea villosa", "Dipsacus fullonum", 
              "Athyrium filix-femina", "Dryopteris campyloptera", "Dryopteris carthusiana", 
              "Dryopteris intermedia", "Onoclea sensibilis", "Woodsia ilvensis",
              "Equisetum hyemale", "Gaylussacia baccata", "Kalmia angustifolia", 
              "Lyonia ligustrina", "Pyrola americana", "Vaccinium macrocarpon", 
              "Vaccinium stamineum", "Eriocaulon aquaticum", "Chamaesyce vermiculata", 
              "Amphicarpa bracteata", "Apios americana", "Baptisia tinctoria", 
              "Desmodium cuspidatum", "Desmodium glutinosum", "Desmodium nudiflorum", 
              "Desmodium paniculatum", "Desmodium rotundifolium", "Lespedeza capitata", 
              "Lespedeza hirta", "Lespedeza intermedia", "Lespedeza violacea", 
              "Robinia pseudo-acacia", "Trifolium aureum", "Trifolium campestre", "Vicia cracca",
              "Castanea mollissima", "Fagus grandifolia", "Quercus bicolor", "Quercus coccinea", 
              "Quercus ilicifolia", "Corydalis sempervirens", "Bartonia virginica", 
              "Gentiana clausa", "Gentianopsis crinita", "Geranium bicknellii", 
              "Geranium maculatum", "Geranium robertianum", "Hamamelis virginiana", 
              "Sisyrinchium mucronatum", "Isoetes echinospora", "Carya cordiformis", 
              "Carya ovalis", "Carya tomentosa", "Juglans cinerea", "Juglans nigra", 
              "Juncus acuminatus", "Juncus brevicaudatus", "Juncus canadensis", "Juncus debilis",
              "Juncus dichotomus", "Juncus effusus", "Juncus marginatus", 
              "Collinsonia canadensis", "Cunila origanoides", "Lycopus virginicus", 
              "Origanum vulgare", "Lemna minor", "Utricularia inflata", "Utricularia minor", 
              "Allium tricoccum", "Allium vineale", "Hemerocallis fulva", "Lilium canadense", 
              "Lilium philadelphicum", "Medeola virginiana", "Streptopus roseus", 
              "Uvularia perfoliata", "Uvularia sessilifolia", "Veratrum viride", 
              "Linum virginianum", "Lycopodium digitatum", "Decodon verticillatus", 
              "Lythrum salicaria", "Rotala ramosior", "Rhexia virginica", 
              "Menispermum canadense", "Nymphoides cordata", "Morus rubra", "Nuphar variegata",
              "Nymphaea odorata", "Nyssa sylvatica", "Fraxinus nigra", "Syringa vulgaris", 
              "Circaea lutetiana", "Epilobium angustifolium", "Epilobium ciliatum", 
              "Epilobium coloratum", "Ludwigia palustris", "Oenothera biennis", 
              "Botrychium dissectum", "Botrychium virginianum", "Corallorhiza odontorhiza", 
              "Cypripedium acaule", "Cypripedium parviflorum", "Goodyera repens", 
              "Malaxis bayardii", "Platanthera flava", "Platanthera lacera", 
              "Platanthera psycodes", "Spiranthes cernua", "Epifagus virginiana", 
              "Osmunda cinnamomea", "Osmunda claytoniana", "Osmunda regalis", 
              "Oxalis corniculata", "Oxalis dillenii", "Oxalis stricta", "Larix decidua", 
              "Larix kaempferi", "Picea glauca", "Picea mariana", "Pinus banksiana", 
              "Pinus rigida", "Pinus strobus", "Plantago lanceolata", "Plantago major", 
              "Plantago rugelii", "Agrostis capillaris", "Agrostis gigantea", 
              "Agrostis stolonifera", "Arrhenatherum elatius", "Avena sativa", 
              "Brachyelytrum septentrionale", "Bromus ciliatus", "Bromus pubescens", 
              "Calamagrostis canadensis", "Calamagrostis cinnoides", "Cinna arundinacea",
              "Digitaria ischaemum", "Echinochloa muricata", "Elymus riparius", 
              "Elymus villosus", "Elytrigia repens", "Festuca subverticillata", 
              "Glyceria melicaria", "Glyceria striata", "Leersia oryzoides", "Lolium perenne", 
              "Lolium pratense", "Microstegium vimineum", "Muhlenbergia schreberi", 
              "Oryzopsis asperifolia", "Oryzopsis racemosa", "Panicum capillare", 
              "Panicum clandestinum", "Panicum commutatum", "Panicum depauperatum", 
              "Panicum dichotomiflorum", "Panicum dichotomum", "Panicum linearifolium", 
              "Panicum rigidulum", "Phalaris arundinacea", "Phragmites australis", "Poa annua", 
              "Poa compressa", "Poa palustris", "Poa pratensis", "Setaria faberi", 
              "Setaria pumila", "Sphenopholis obtusata", "Polygala sanguinea", 
              "Polygala verticillata", "Polygonum arifolium", "Polygonum cuspidatum", 
              "Polygonum pensylvanicum", "Rumex crispus", "Rumex obtusifolius", 
              "Rumex orbiculatus", "Pontederia cordata", "Potamogeton natans", 
              "Lysimachia ciliata", "Trientalis borealis", "Anemone virginiana", 
              "Caltha palustris", "Hepatica nobilis", "Ranunculus acris", "Ranunculus ambigens", 
              "Ranunculus bulboses", "Ranunculus micranthus", "Thalictrum pubescens", 
              "Ceanothus americanus", "Agrimonia gryposepala", "Aronia arbutifolia", 
              "Aronia melanocarpa", "Crataegus macrosperma", "Geum canadense", "Geum laciniatum",
              "Physocarpus opulifolius", "Potentilla argentea", "Potentilla arguta", 
              "Potentilla norvegica", "Potentilla recta", "Potentilla simplex", 
              "Prunus domestica", "Prunus pensylvanica", "Prunus pumila", "Prunus serotina", 
              "Pyrus communis", "Rosa carolina", "Rosa palustris", "Rubus flagellaris", 
              "Rubus idaeus", "Rubus odoratus", "Rubus pensylvanicus", "Rubus phoenicolasius",
              "Spirea tomentosa", "Galium aperellum", "Galium boreale", "Galium lanceolatum", 
              "Galium mollugo", "Galium tinctorum", "Galium trifidum", "Populus deltoides", 
              "Populus tremuloides", "Salix bebbiana", "Salix discolor", "Salix eriocephala", 
              "Salix humilis", "Salix lucida", "Salix nigra", "Salix purpurea", 
              "Comandra umbellata", "Sarracenia purpurea", "Heuchera americana", 
              "Saxifraga virginiensis", "Aureolaria flava", "Aureolaria pedicularia", 
              "Aureolaria virgininica", "Chelone glabra", "Penstemon tubaeflorus", 
              "Verbascum blattaria", "Verbascum thapsus", "Veronica americana", 
              "Veronica scutellata", "Selaginella rupestris", "Ailanthus altissima", 
              "Smilax herbacea", "Solanum nigrum", "Staphylea trifolia", 
              "Phegopteris connectilis", "Phegopteris hexagonoptera", "Thelypteris palustris", 
              "Woodwardia virginica", "Tilia americana", "Ulmus americana", 
              "Laportea canadensis", "Pilea pumila", "Phyrma leptostachya", "Verbena hastata", 
              "Verbena urticifolia", "Viola affinis", "Viola macloskeyi", "Viola palmata", 
              "Viola sagittata", "Vitis aestivalis", "Vitis riparia")

BRF_genus <- c("Acer", "Achillea", "Actaea", "Adiantum", "Agalinis", "Agrimonia", "Agrostis", 
               "Ailanthus", "Ajuga", "Alisma", "Alliaria", "Allium", "Alnus", "Ambrosia", 
               "Amelanchier", "Amphicarpa", "Anaphalis", "Andropogon", "Anemone", "Angelica", 
               "Antennaria", "Anthoxanthum", "Apios", "Apocynum", "Aquilegia", "Arabis", 
               "Aralia", "Arctium", "Arisaema", "Aristolochia", "Aronia", "Arrhenatherum", 
               "Asarum", "Asclepias", "Asplenium", "Aster", "Athyrium", "Aureolaria", "Avena", 
               "Baptisia", "Barbarea", "Bartonia", "Berberis", "Betula", "Bidens", 
               "Botrychium", "Brachyelytrum", "Brassica", "Bromus", "Calamagrostis", "Calla", 
               "Callitriche", "Caltha", "Calystegia", "Campanula", "Capsella", "Cardamine", 
               "Carex", "Carpinus", "Carya", "Castanea", "Catalpa", "Caulophyllum", 
               "Ceanothus", "Celastrus", "Centaurea", "Cephalanthus", "Cerastium", 
               "Chamaedaphne", "Chamaesyce", "Chelidonium", "Chelone", "Chenopodium", 
               "Chimaphila", "Chrysosplenium", "Cichorium", "Cicuta", "Cinna", "Circaea", 
               "Cirsium", "Clematis", "Clethra", "Clinopodium", "Collinsonia", "Comandra", 
               "Commelina", "Comptonia", "Conioselinum", "Conium", "Conopholis", "Convolvulus",
               "Conyza", "Corallorhiza", "Cornus", "Corydalis", "Corylus", "Crataegus", 
               "Cryptotaenia", "Cunila", "Cuscuta", "Cynanchum", "Cyperus", "Cypripedium", 
               "Dactylis", "Danthonia", "Daucus", "Decodon", "Dennstaedtia", "Deschampsia", 
               "Desmodium", "Dianthus", "Dicentra", "Dichanthelium", "Diervilla", "Digitaria", 
               "Dioscorea", "Dipsacus", "Dirca", "Drosera", "Dryopteris", "Dulichium", 
               "Echinochloa", "Echium", "Eleocharis", "Elodea", "Elymus", "Elytrigia", 
               "Epifagus", "Epigaea", "Epilobium", "Epipactis", "Equisetum", "Erectites", 
               "Erigeron", "Eriocaulon", "Erythronium", "Euonymus", "Eupatorium", "Euphorbia", 
               "Euthamia", "Fagus", "Festuca", "Fragaria", "Fraxinus", "Galinsoga", "Galium", 
               "Gaultheria", "Gaylussacia", "Gentiana", "Gentianopsis", "Geranium", "Geum", 
               "Glyceria", "Gnaphalium", "Goodyera", "Gratiola", "Gyrophora", "Hamamelis", 
               "Hedeoma", "Helianthemum", "Helianthus", "Heliopsis", "Hemerocallis", "Hepatica", 
               "Heracleum", "Hesperis", "Heuchera", "Hieracium", "Humulus", "Huperzia", 
               "Hydrocotyle", "Hypericum", "Hypoxis", "Ilex", "Impatiens", "Iris", "Isoetes", 
               "Juglans", "Juncus", "Juniperus", "Krigia", "Lactuca", "Laportea", "Lapsana", 
               "Larix", "Lechea", "Leersia", "Lemna", "Leonurus", "Lepidium", "Lespedeza", 
               "Leucanthemum", "Lilium", "Lindera", "Linum", "Liriodendron", "Lobelia", "Lolium",
               "Lonicera", "Lotus", "Ludwigia", "Luzula", "Lychnis", "Lycopodium", "Lycopus", 
               "Lyonia", "Lysimachia", "Lythrum", "Maianthemum", "Malaxis", "Malus", "Medeola", 
               "Melampyrum", "Melilotus", "Menispermum", "Mentha", "Microstegium", "Mimulus", 
               "Mitchella", "Mitella", "Monotropa", "Morus", "Muhlenbergia", "Myosotis", 
               "Nemopanthus", "Nepeta", "Nuphar", "Nymphaea", "Nymphoides", "Nyssa", "Oenothera",
               "Onoclea", "Origanum", "Ornithogalum", "Orobanche", "Oryzopsis", "Osmorhiza", 
               "Osmunda", "Ostrya", "Oxalis", "Pachysandra", "Panax", "Panicum", "Paronychia", 
               "Parthenocissus", "Pedicularis", "Peltandra", "Penstemon", "Penthorum", 
               "Phalaris", "Phegopteris", "Phleum", "Phragmites", "Phyrma", "Physocarpus", 
               "Phytolacca", "Pinus", "Plantago", "Platanthera", "Platanus", "Poa", "Polygala", 
               "Polygonatum", "Polygonum", "Polypodium", "Polystichum", "Pontederia", "Populus", 
               "Potamogeton", "Potentilla", "Prenanthes", "Prunella", "Prunus", "Pteridium", 
               "Pycnanthemum", "Pyrola", "Pyrus", "Quercus", "Ranunculus", "Rhamnus", "Rhexia", 
               "Rhododendron", "Rhus", "Ribes", "Robinia", "Rorippa", "Rosa", "Rotala", "Rubus", 
               "Rudbeckia", "Rumex", "Sagina", "Sagittaria", "Salix", "Sambucus", "Sanicula", 
               "Sarracenia", "Sassafras", "Saxifraga", "Schizachyrium", "Scirpus", 
               "Scleranthus", "Scutellaria", "Sedum", "Selaginella", "Senecio", "Setaria", 
               "Silene", "Sinapsis", "Sisyrinchium", "Sium", "Smilax", "Solanum", "Solidago", 
               "Sorghastrum", "Sparganium", "Sphagnum", "Sphenopholis", "Spiranthes", "Spirea", 
               "Staphylea", "Stellaria", "Streptopus", "Symphyotrichum", "Symplocarpus", 
               "Syringa", "Taraxacum", "Thalictrum", "Thelypteris", "Thlaspi", "Tilia", 
               "Toxicodendron", "Triadenum", "Trientalis", "Trifolium", "Trillium", "Triodanis", 
               "Tsuga", "Tussilago", "Tyhpa", "Ulmus", "Umbilicaria", "Utricularia", "Uvularia", 
               "Vaccinium", "Veratrum", "Verbascum", "Verbena", "Veronica", "Viburnum", "Vicia", 
               "Viola", "Woodsia", "Woodwardia", "Xanthium", "Zizia")

BRF_family <- c("Aceraceae", "Alismataceae", "Anacardiaceae", "Apiaceae", "Apocynaceae", 
                    "Aquifoliaceae", "Araceae", "Araliaceae", "Aristolochiaceae", 
                    "Asclepiadaceae", "Aspleniaceae", "Asteraceae", "Balsaminaceae", 
                    "Berberidaceae", "Betulaceae", "Bignoniaceae", "Boraginaceae", 
                    "Brassicaceae", "Buxaceae", "Cabombaceae", "Callitrichaceae", 
                    "Campanulaceae", "Cannabaceae", "Caprifoliaceae", "Caryophyllaceae", 
                    "Celastraceae", "Chenopodiaceae", "Cistaceae", "Clethraceae", "Clusiaceae", 
                    "Commelinaceae", "Convolvulaceae", "Cornaceae", "Crassulaceae", 
                    "Cupressaceae", "Cuscutaceae", "Cyperaceae", "Dennstaedtiaceae", 
                    "Dioscoreaceae", "Dipsacaceae", "Droseraceae", "Dryopteridaceae", 
                    "Equisetaceae", "Ericaceae", "Eriocaulaceae", "Euphorbiaceae", "Fagaceae", 
                    "Fumariaceae", "Gentianaceae", "Geraniaceae", "Grossulariaceae", 
                    "Hamamelidaceae", "Hydrocharitaceae", "Iridaceae", "Isoetaceae", 
                    "Juglandaceae", "Juncaceae", "Lemnaceae", "Lentibulariaceae", "Liliaceae", 
                    "Linaceae", "Lycopodiaceae", "Lythraceae", "Magnoliaceae", "Melastomataceae",
                    "Menispermaceae", "Menyanthaceae", "Moraceae", "Myricaceae", "Nymphaeaceae", 
                    "Nyssaceae", "Oleaceae", "Onagraceae", "Ophioglossaceae", "Orchidaceae", 
                    "Orobanchaceae", "Osmundaceae", "Oxalidaceae", "Papaveraceae", 
                    "Phytolaccaceae", "Pinaceae", "Plantaginaceae", "Platanaceae", "Poaceae", 
                    "Polygalaceae", "Polygonaceae", "Polypodiaceae", "Pontederiaceae", 
                    "Potamogetonaceae", "Primulaceae", "Pteridiaceae", "Pyrolaceae", 
                    "Ranunculaceae", "Rhamnaceae", "Rosaceae", "Rubiaceae", "Salicaceae", 
                    "Santalaceae", "Sarraceniaceae", "Saxifragaceae", "Scrophulariaceae", 
                    "Selaginellaceae", "Simaroubaceae", "Smilacaceae", "Solanaceae", 
                    "Sparganiaceae", "Sphagnaceae", "Staphyleaceae", "Thelypteridaceae", 
                    "Thymelaeaceae", "Tiliaceae", "Typhaceae", "Ulmaceae", "Umbilicariaceae", 
                    "Urticaceae", "Verbenaceae", "Violaceae", "Vitaceae")

colden_full <- c("Sambucus canadensis", "Alisma trivialis", "Sagittaria latifolia", 
                 "Asclepias tuberosa", "Arisaema triphyllum", "Aralia nudicaulis", 
                 "Asarum canadense", "Aristolochia serpentaria", "Maianthemum racemosum", 
                 "Maianthemum canadense", "Solidago squarrosa", "Pseudognaphalium obtusifolium", 
                 "Ambrosia artemisiifolia", "Rudbeckia triloba", "Helenium autumnale", 
                 "Cardamine diphylla", "Lobelia cardinalis", "Cornus florida", 
                 "Kalmia angustifolia", "Baptisia tinctoria", "Lupinus perennis", 
                 "Apios americana", "Quercus alba", "Monarda didyma", "Hedeoma pulegioides", 
                 "Pycnanthemum incanum", "Collinsonia canadensis", "Lilium philadelphicum", 
                 "Lilium superbum", "Erythronium americanum", "Medeola virginiana", 
                 "Trillium erectum", "Ludwigia palustris", "Circaea lutetiana", 
                 "Cypripedium calceolus", "Calopogon tuberosus", "Aureolaria virginica", 
                 "Melampyrum lineare", "Pedicularis canadensis", "Sanguinaria canadensis", 
                 "Mimulus ringens", "Phytolacca icosandra", "Chelone glabra", 
                 "Veronicastrum virginicum", "Polygala senega", "Lysimachia quadrifolia", 
                 "Lysimachia ciliata", "Hepatica nobilis", "Caltha palustris", "Coptis trifolia",
                 "Rubus odoratus", "Sarracenia purpurea", "Saururus cernuus", "Mitella diphylla",
                 "Micranthes virginiensis", "Verbascum blattaria", "Staphylea trifolia", 
                 "Verbena hastata")

colden_genus <- c("Alisma", "Ambrosia", "Apios", "Aralia", "Arisaema", "Aristolochia", 
                  "Asarum", "Asclepias", "Aureolaria", "Baptisia", "Calopogon", "Caltha", 
                  "Cardamine", "Chelone", "Circaea", "Collinsonia", "Coptis", "Cornus", 
                  "Cypripedium", "Erythronium", "Hedeoma", "Helenium", "Hepatica", 
                  "Kalmia", "Lilium", "Lobelia", "Ludwigia", "Lupinus", "Lysimachia", 
                  "Maianthemum", "Medeola", "Melampyrum", "Micranthes", "Mimulus", "Mitella", 
                  "Monarda", "Pedicularis", "Phytolacca", "Polygala", "Pseudognaphalium", 
                  "Pycnanthemum", "Quercus", "Rubus", "Rudbeckia", "Sagittaria", "Sambucus", 
                  "Sanguinaria", "Sarracenia", "Saururus", "Solidago", "Staphylea", "Trillium", 
                  "Verbascum", "Verbena", "Veronicastrum")

colden_family <- c("Adoxaceae", "Alismataceae", "Apocynaceae", "Araceae", "Araliaceae",
                   "Aristolochiaceae", "Asparagaceae", "Asteraceae", "Brassicaceae",
                   "Campanulaceae", "Cornaceae", "Ericaceae", "Fabaceae", "Fagaceae", 
                   "Lamiaceae", "Liliaceae", "Melanthiaceae", "Onagraceae", "Orchidaceae", 
                   "Orobanchaceae", "Papaveraceae", "Phrymaceae", "Phytolaccaceae", 
                   "Plantaginaceae", "Polygalaceae", "Primulaceae", "Ranunculaceae", "Rosaceae", 
                   "Sarraceniaceae", "Saururaceae", "Saxifragaceae", "Scrophulariaceae", 
                   "Staphyleaceae", "Verbenaceae")

length(unique(BRF_full))
length(unique(colden_full))
length(unique(colden_genus))
length(unique(colden_family))
intersect(BRF_full, colden_full)
intersect(BRF_genus, colden_genus)
intersect(BRF_family, colden_family)
